name: Check for New Episodes

on:
  schedule:
    - cron: '0 0 * * 1'  # Her Pazartesi 00:00'da (UTC)
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Check for new episode
      id: episode_check
      run: |
        OUTPUT=$(python scripts/check_new_episode.py)
        echo "output=$OUTPUT" >> $GITHUB_OUTPUT
        if [[ $OUTPUT == *"Yeni bölüm bulundu"* ]]; then
          echo "new_episode=true" >> $GITHUB_OUTPUT
          EPISODE_NUMBER=$(echo $OUTPUT | grep -oP 'Bölüm \K\d+')
          echo "episode_number=$EPISODE_NUMBER" >> $GITHUB_OUTPUT
        else
          echo "new_episode=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if new episode
      if: steps.episode_check.outputs.new_episode == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add kurulus-osman.m3u last_episode.txt
        git commit -m "Otomatik güncelleme: Yeni bölüm ${{ steps.episode_check.outputs.episode_number }} eklendi"
        git push
