name: M3U Playlist Generator

on:
  workflow_dispatch:  # Manuel çalıştırma
  schedule:
    - cron: '0 0 * * 1'  # Haftalık otomatik kontrol (Pazartesi)

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Generate and Check Updates
      run: |
        if [ ! -f "last_episode.txt" ]; then
          echo "194" > last_episode.txt
        fi
        python generate_m3u.py
        
    - name: Commit Changes
      if: contains(steps.generate.outputs.log, 'Güncellendi')
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add kurulus-osman.m3u last_episode.txt
        git commit -m "Otomatik güncelleme: $(date '+%d.%m.%Y')"
        git push
