name: M3U Playlist Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Her Pazartesi

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Generate M3U
      id: generate
      run: |
        python generate_m3u.py
        echo "status=$(grep -q '::set-output name=status::updated' generate_m3u.py && echo 'updated' || echo 'no_update')" >> $GITHUB_OUTPUT
    
    - name: Commit Changes
      if: steps.generate.outputs.status == 'updated'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add kurulus-osman.m3u last_episode.txt
        git commit -m "Otomatik güncelleme: $(date '+%d.%m.%Y')"
        git push
